GET localhost:8080/products
Authorization: Basic quynhnhi@gmail.com 12345

###

GET localhost:8080/products
Authorization: Basic tanhung@gmail.com 12345

###

POST localhost:8080/products
Authorization: Basic tanhung@gmail.com 12345
Content-Type: application/json

{
  "name": "ASUS",
  "price": 123
}